### PR TITLE
remove unused package imports; add needed get_var_char_values function

### PR DESCRIPTION
**Pull request by msropp**
The code would not run with no definition for `get_var_char_values()`

### CODE REVIEW

**Comment by msropp** [comment]
Thanks for your very helpful code @raoofnaushad!

**Review by KarlAloYoga — APPROVED** [review]

**Comment by msropp** [comment]
Thank you for the review @KarlAloYoga  Can anyone merge this if all looks good? Thank you!   @raoofnaushad

**Comment by msropp** [comment]
@raoofnaushad

**Comment by tjdahlke** [comment]
Just wanted to comment that this PR does seem to be a necessary fix. Flagging @raoofnaushad.

**Pull request merged**
